### ISSUE TITLE
old role that only runs in kubelet rpm is installed

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomic-host-tests#99]
https://github.com/projectatomic/atomic-host-tests/blob/0ad1a20/roles/semanage_add_verify/tasks/main.yml#L3

We should refocus this role or get rid of it as it only runs if kubelet rpm is installed and that is no longer an rpm in fedora or CAHC.

**Comment by miabbott** [comment]
The tasks that run after the check attempt to change the file context on a directory that happens to be `/var/lib/kubelet`.  I think this was chosen because it was the directory that the OpenShift folks were manipulating in their installer. (Don't quote me on that...)

The BZ ([#1398427](https://bugzilla.redhat.com/show_bug.cgi?id=1398427)) that necessitated this test was modifying contexts on another directory, so we don't necessarily have to use the `/var/lib/kubelet` directory for this test.

I think this is still a valuable test and we should just pick (or create) an arbitrary directory that we fiddle with.

**Comment by miabbott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Update semanage test in [a-h-t] to use alternate directory](https://trello.com/c/PE4epFwh/678-2-update-semanage-test-in-a-h-t-to-use-alternate-directory)
